mozilla/Jisort

app/app.iml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/events/BatteryStateChanged.java, app/src/main/java/com/mozilla/hackathon/kiboko/events/LocationStateChanged.java, app/src/main/java/com/mozilla/hackathon/kiboko/events/NetworkStateChanged.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/TopicsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOBatteryReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOLocationReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSONetworkStateReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/ChatHeadService.java, app/src/main/java/com/mozilla/hackathon/kiboko/utilities/LogUtils.java, app/src/main/java/com/mozilla/hackathon/kiboko/widgets/DSOGridView.java, app/src/main/java/com/mozilla/hackathon/kiboko/widgets/MessageCardView.java, app/src/main/res/layout/dashboard_layout.xml, app/src/main/res/layout/fragment_topics_layout.xml, app/src/main/res/layout/message_card.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/placeholder_strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
* fixed GridView collapsing inside scrollview with DSOGridView modified view
* Suggested topics. (Shows banners on dashboard)
=> Sugeested Topics UI

app/app.iml, app/src/main/AndroidManifest.xml, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/MainActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/QuizActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/ResultActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOLocationReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/ChatHeadService.java, app/src/main/java/com/mozilla/hackathon/kiboko/utilities/Utils.java, app/src/main/java/com/mozilla/hackathon/kiboko/widgets/CheckableLinearLayout.java, app/src/main/res/layout/service_floating_button.xml
* Resolves #1 
* Fixes warn user on exiting Quiz screen.
* Back button works on Result Screen of Quiz flow.
* Open app from icon.
* "Suggested topics" Learn more link to tutorials.
* The "<" button to go to the previous tutorial step doesn't work.
=> Bug fixes from 14-06-2016

app/app.iml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/adapters/TopicsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/ScreenSlidePageFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/TopicsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/io/JSONHandler.java, app/src/main/java/com/mozilla/hackathon/kiboko/io/TutorialsHandler.java, app/src/main/java/com/mozilla/hackathon/kiboko/models/Step.java, app/src/main/java/com/mozilla/hackathon/kiboko/models/Tutorial.java, app/src/main/java/com/mozilla/hackathon/kiboko/provider/DsoContract.java, app/src/main/java/com/mozilla/hackathon/kiboko/provider/DsoDatabase.java, app/src/main/java/com/mozilla/hackathon/kiboko/provider/DsoProvider.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/ChatHeadService.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/DataBootstrapService.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/SyncHelper.java, app/src/main/java/com/mozilla/hackathon/kiboko/sync/DsoDataHandler.java, app/src/main/res/layout/fragment_screen_slide_page.xml, app/src/main/res/raw/bootstrap_data.json, artifacts.gradle, build.gradle, gradle.properties, versioning.gradle
* App versioning and naming.
* Content functionality
=> MVP of Content functionality.

app/app.iml, app/src/main/AndroidManifest.xml, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TopicListActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/adapters/IconsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/ScreenSlidePageFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/TopicsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOAirplaneModeReceiver.java, gradle.properties
* Fixes crashing caused by invalid cast of gif images.
* Updated icons screen.
=> Fixes casting bug

app/src/main/res/layout/fragment_screen_slide_page.xml
To put gifs on top of text in tutorials.
fixes #28
=> moved GifImageView on top of HtmlTextView

README.md, app/app.iml, app/src/main/AndroidManifest.xml, app/src/main/java/com/mozilla/hackathon/kiboko/Config.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/ScreenSlidePageFragment.java, app/src/main/res/layout/fragment_screen_slide_page.xml, doc/BUILDING.md, doc/CUSTOM.md, doc/SYNC.md
Updating documentation to allow quick setup and bootstrapping of app by other interested parties.
=> Updating documentation

app/src/main/java/com/mozilla/hackathon/kiboko/adapters/IconsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/IconsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/models/IconTopic.java
1. Made IconTopic based on Topic to be Icon-specific.
2. Added titles to to IconsFragment.
3. Added code to manipulate tooltip title.
4. Adjusted from Topic to IconTopic appropriately.
=> Added titles to icon tooltips.

CREDITS.md
=> Added credits file with various credits

app/src/main/java/com/mozilla/hackathon/kiboko/activities/DSOActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/FindIconsActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/SplashActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TabLayoutActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TopicListActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/events/ApplicationStateChanged.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/ChatHeadService.java
1. Extended all appropriate activities from new DSOActivity.
2. DSOActivity watches for resume/pause and fires ApplicationStateChanged activity on bus.
3. Added DSOActivity.
4. Added ApplicationStateChanged.
Fixes #29.
=> FAB becomes [in]visible depending on app state

app/src/main/java/com/mozilla/hackathon/kiboko/Analytics.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/adapters/TopicsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/TopicsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/ChatHeadService.java
1. Created Analytics class.
2. Added Analytics tracking to various places.
=> Simple Analytics

app/src/main/java/com/mozilla/hackathon/kiboko/activities/IconQuizActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/ResultActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/utilities/SelectionBuilder.java, app/src/main/res/layout/activity_icon_quiz.xml, app/src/main/res/layout/activity_result.xml, app/src/main/res/values/strings.xml
=> Merge deeplinking fixes.

app/src/main/res/raw/bootstrap_data.json
=> Merging contentFixes

app/app.iml, app/src/main/java/com/mozilla/hackathon/kiboko/App.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/IconQuizActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/adapters/IconsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/adapters/TopicsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/IconsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/fragments/TopicsFragment.java, app/src/main/java/com/mozilla/hackathon/kiboko/services/ChatHeadService.java, app/src/main/res/drawable/circular_wifi.xml, app/src/main/res/drawable/popup_border.xml, app/src/main/res/layout/fragment_icons_layout.xml, app/src/main/res/layout/tooltip_dso.xml, app/src/main/res/raw/bootstrap_data.json, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, gradle.properties
resolves #74 
resolves #64 
resolves #59 
resolves #70
=> Merging Iconquiz bugfixes

app/app.iml, app/src/main/res/raw/keep.xml
* resolves #101 
* resloves #95 
* resolves #93
=> Merges missing gifs due to resourceshrinking.

app/src/main/res/raw/bootstrap_data.json
=> switched from Title Bar to Notification Bar

app/src/main/res/raw/bootstrap_data.json
Added warning about hotspots and data bundle usage.
=> Fixes #107.

app/src/main/java/com/mozilla/hackathon/kiboko/activities/IconQuizActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/ResultActivity.java, app/src/main/res/layout/activity_icon_quiz.xml, app/src/main/res/layout/activity_result.xml, app/src/main/res/values/strings.xml
Fixes #163.
1. Cleaned up strings for quiz and result.
2. Added logic to display score.
=> Better score readout in quiz.

app/src/main/res/raw/bootstrap_data.json
Fixes #164.
Also fixes a broken bit of html.
=> Add example to password tutorial

app/src/main/AndroidManifest.xml, app/src/main/java/com/mozilla/hackathon/kiboko/App.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/DashboardActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/WelcomeActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/settings/SettingsUtils.java, app/src/main/res/layout/activity_welcome.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, gradle.properties
* Removes actionbar from welcome screen. References #170 
* Refactored Welcome screen to use helper file for settings. References #170
* Reverted dashboard title. References #76
=> Merging in updates

app/src/main/res/layout/fragment_icons_layout.xml, app/src/main/res/values/strings.xml
1. Moved text + button to the top.
2. Added text about learning.
3. Changed text on button to make it more engaging.
=> Fixes to the layout of the icon fragment.

gradle/wrapper/gradle-wrapper.properties
=> Update Gradle wrapper version to meet minimum requirements

app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java
Resets the scroll position to the top of the page (0,0) when someone transitions to the page, relatively straight forward patch. If anyone is available I'd really appreciate a review.
cc: @secretrobotron 
Closes #144
=> Fix ScrollView not resetting scroll position between fragments, Closes #144

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/layout/fragment_icons_layout.xml, app/src/main/res/layout/topiclist_layout.xml, app/src/main/res/menu/activity_tutorial_slide.xml
=> Resolve Android linting errors

app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java
This is a much nicer solution to the problem than my previous one, there doesn't appear to be any straight forward way of doing this unfortunately. On a positive note, this doesn't crash ^.^
=> Reset page scroll position on *transition* to page, Closes #222

app/src/main/java/com/mozilla/hackathon/kiboko/Analytics.java, app/src/main/java/com/mozilla/hackathon/kiboko/App.java, app/src/main/java/com/mozilla/hackathon/kiboko/activities/TutorialSlideActivity.java, app/src/main/java/com/mozilla/hackathon/kiboko/adapters/IconsAdapter.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOAirplaneModeReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOBatteryReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSONetworkStateReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/recievers/DSOStorageReceiver.java, app/src/main/java/com/mozilla/hackathon/kiboko/utils/NetworkUtils.java, app/src/main/java/com/mozilla/hackathon/kiboko/utils/UiUtils.java
=> Fix notification state for wifi, airplane mode, and low battery with small refactorings

.travis.yml
Not finished yet, needs:
* keys added
* find out if you want the whole output of `app/build/outputs/apk` uploaded to the root of the s3 bucket or a specific folder.
=> #213 added initial s3 config

.travis.yml
Improve build times by utilizing cache functionality to cache Gradle library files.
=> Travis CI Optimizations

app/src/main/AndroidManifest.xml
=> Remove intent host field, surpress missing field lint error (Fixes #234)

app/build.gradle
Library changelog https://github.com/douglasjunior/android-simple-tooltip/releases/tag/0.1.2
=> updated android-simple-tooltip to prevent unspected crashes

.travis.yml, app/build.gradle, build.gradle, third_party/HtmlTextView/build.gradle
Updates target Android version to API 25 (latest), also updates all development and build dependencies to latest versions for general performance, bug and stability improvements.
Resolves #218
=> Update dependencies to latest versions
